---
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
grails:
    codegen:
        defaultPackage: mlm
    profile: web

---
grails:
    views:
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                scriptlet: html

---


environments:
   development:
    grails:
       
      mongodb:
        host: "localhost"
        port: 27017
        username: ""
        password: ""
        databaseName: "mlm"
    production:
     grails:
       mongodb:
               url: "mongodb+srv://subjectid:123321@cluster0.mq9xlid.mongodb.net/mlm?appName=Cluster0"